const analyzePrompt = (prompt) => {
  const promptLower = prompt.toLowerCase();
  
  let language = 'Node.js/Express'; // default
  let schema = getNodeExpressSchema(); // default schema

  if (promptLower.includes('next') || promptLower.includes('next.js') || promptLower.includes('nextjs')) {
    language = 'Next.js';
    schema = getNextJsSchema();
  } else if (promptLower.includes('rust') || promptLower.includes('cargo') || promptLower.includes('axum') || promptLower.includes('actix')) {
    language = 'Rust';
    schema = getRustSchema();
  } else if (promptLower.includes('c#') || promptLower.includes('.net') || promptLower.includes('dotnet') || promptLower.includes('webapi')) {
    language = 'C#/.NET';
    schema = getCSharpDotnetSchema();
  } else if (promptLower.includes('python') || promptLower.includes('fastapi') || promptLower.includes('flask')) {
    language = 'Python/FastAPI';
    schema = getPythonFastAPISchema();
  } else if (promptLower.includes('c++') || promptLower.includes('cpp') || promptLower.includes('cmake')) {
    language = 'C++/CMake';
    schema = getCppCMakeSchema();
  } else if (promptLower.includes('node') || promptLower.includes('express')) {
    language = 'Node.js/Express';
    schema = getNodeExpressSchema();
  }

  return {
    language,
    schema,
    message: `Architect analyzed requirements, identified ${language} project.`
  };
};

// Next.js (App Router) Schema
const getNextJsSchema = () => ({
  language: 'Next.js',
  projectName: 'architech-next-app',
  dependencies: ['react', 'react-dom', 'next'],
  database: 'sqlite',
  directoryTree: {
    paths: [
      'package.json',
      'next.config.js',
      'tsconfig.json',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md',
      'src/app/page.tsx',
      'src/app/layout.tsx',
      'src/app/globals.css',
      'src/components/Header.tsx',
      'src/components/Footer.tsx'
    ]
  },
  fileContents: {
    'package.json': JSON.stringify({
      name: "architech-next-app",
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        next: "14.2.3",
        react: "^18.3.1",
        "react-dom": "^18.3.1"
      },
      devDependencies: {
        "@types/node": "^20.14.0",
        "@types/react": "^18.3.3",
        "@types/react-dom": "^18.3.0",
        typescript: "^5.4.5"
      }
    }, null, 2),
    'next.config.js': '/** @type {import(\'next\').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true,\n};\n\nmodule.exports = nextConfig;',
    'tsconfig.json': JSON.stringify({
      compilerOptions: {
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: {
          "@/*": ["./src/*"]
        }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2),
    '.gitignore': '# Dependencies\nnode_modules/\n\n# Build artifacts\n.next/\n\n# IDE\n.vscode/\n.idea/\n\n# Environment variables\n.env\n.env.local\n\n# Logs\n*.log',
    'Dockerfile': 'FROM node:20-slim AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-slim\nWORKDIR /app\nCOPY --from=builder /app/.next ./.next\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY --from=builder /app/package.json ./package.json\nEXPOSE 3000\nCMD ["npm", "start"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.\nPlease replace this content with your own documentation.',
    'src/app/page.tsx': 'export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-between p-24">\n      <h1 className="text-4xl font-bold">Welcome to ArchiTech Next.js App</h1>\n      <p className="text-xl mt-4">Your autonomous project scaffolder!</p>\n    </main>\n  )\n}',
    'src/app/layout.tsx': 'import type { Metadata } from "next";\nimport "./globals.css";\nimport Header from "@/components/Header";\nimport Footer from "@/components/Footer";\n\nexport const metadata: Metadata = {\n  title: "ArchiTech App",\n  description: "Generated by ArchiTech",\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang="en">\n      <body>\n        <Header />\n        {children}\n        <Footer />\n      </body>\n    </html>\n  );\n}',
    'src/app/globals.css': '* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\n\nbody {\n  font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', \'Roboto\', sans-serif;\n}',
    'src/components/Header.tsx': 'export default function Header() {\n  return (\n    <header className="bg-blue-600 text-white p-4 shadow-lg">\n      <div className="container mx-auto">\n        <h1 className="text-2xl font-bold">ArchiTech</h1>\n      </div>\n    </header>\n  );\n}',
    'src/components/Footer.tsx': 'export default function Footer() {\n  return (\n    <footer className="bg-gray-100 text-center p-6 mt-12">\n      <p className="text-gray-600">© 2025 ArchiTech. All rights reserved.</p>\n    </footer>\n  );\n}'
  }
});

// Rust (Cargo) Schema
const getRustSchema = () => ({
  language: 'Rust',
  projectName: 'architech-rust-app',
  dependencies: ['tokio', 'axum', 'serde', 'serde_json'],
  database: 'sqlite',
  directoryTree: {
    paths: [
      'Cargo.toml',
      'Cargo.lock',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md',
      'src/main.rs'
    ]
  },
  fileContents: {
    'Cargo.toml': '[package]\nname = "architech-rust-app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\ntokio = { version = "1.35", features = ["full"] }\naxum = "0.7"\nserde = { version = "1.0", features = ["derive"] }\nserde_json = "1.0"',
    '.gitignore': '# Dependencies\ntarget/\n\n# IDE\n.vscode/\n.idea/\n\n# Environment variables\n.env\n.env.local\n\n# Logs\n*.log',
    'Dockerfile': 'FROM rust:1.75-slim AS builder\nWORKDIR /app\nCOPY . .\nRUN cargo build --release\n\nFROM debian:bookworm-slim\nWORKDIR /app\nCOPY --from=builder /app/target/release/architech-rust-app .\nEXPOSE 3000\nCMD ["./architech-rust-app"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.\nPlease replace this content with your own documentation.',
    'src/main.rs': 'use axum::{routing::get, Router};\nuse std::net::SocketAddr;\n\nasync fn root() -> &\'static str {\n    "Hello from ArchiTech Rust!"\n}\n\n#[tokio::main]\nasync fn main() {\n    let app = Router::new().route("/", get(root));\n\n    let addr = SocketAddr::from(([0, 0, 0, 0], 3000));\n    println!("🚀 Server running on {}", addr);\n\n    axum::Server::bind(&addr)\n        .serve(app.into_make_services())\n        .await\n        .expect("Failed to start server");\n}'
  }
});

// C#/.NET Web API Schema
const getCSharpDotnetSchema = () => ({
  language: 'C#/.NET',
  projectName: 'architech-dotnet-api',
  dependencies: ['Microsoft.AspNetCore.OpenApi', 'Swashbuckle.AspNetCore'],
  database: 'sqlite',
  directoryTree: {
    paths: [
      'ArchiTechDotnetApi.sln',
      'ArchiTechDotnetApi/ArchiTechDotnetApi.csproj',
      'ArchiTechDotnetApi/Program.cs',
      'ArchiTechDotnetApi/Controllers/WeatherForecastController.cs',
      'ArchiTechDotnetApi/Models/WeatherForecast.cs',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md'
    ]
  },
  fileContents: {
    'ArchiTechDotnetApi.sln': '\nMicrosoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\nVisualStudioVersion = 17.0.31903.59\nMinimumVisualStudioVersion = 10.0.40219.1\nProject("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ArchiTechDotnetApi", "ArchiTechDotnetApi\\ArchiTechDotnetApi.csproj", "{A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D}"\nEndProject\nGlobal\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n\t\tDebug|Any CPU = Debug|Any CPU\n\t\tRelease|Any CPU = Release|Any CPU\n\tEndGlobalSection\n\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n\t\t{A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n\t\t{A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D}.Debug|Any CPU.Build.0 = Debug|Any CPU\n\t\t{A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D}.Release|Any CPU.ActiveCfg = Release|Any CPU\n\t\t{A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D}.Release|Any CPU.Build.0 = Release|Any CPU\n\tEndGlobalSection\nEndGlobal',
    'ArchiTechDotnetApi/ArchiTechDotnetApi.csproj': '<Project Sdk="Microsoft.NET.Sdk.Web">\n\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n\n  <ItemGroup>\n    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.3" />\n    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />\n  </ItemGroup>\n\n</Project>',
    'ArchiTechDotnetApi/Program.cs': 'var builder = WebApplication.CreateBuilder(args);\n\nbuilder.Services.AddControllers();\nbuilder.Services.AddEndpointsApiExplorer();\nbuilder.Services.AddSwaggerGen();\n\nvar app = builder.Build();\n\nif (app.Environment.IsDevelopment())\n{\n    app.UseSwagger();\n    app.UseSwaggerUI();\n}\n\napp.UseHttpsRedirection();\napp.UseAuthorization();\napp.MapControllers();\napp.Run();',
    'ArchiTechDotnetApi/Controllers/WeatherForecastController.cs': 'using Microsoft.AspNetCore.Mvc;\n\nnamespace ArchiTechDotnetApi.Controllers;\n\n[ApiController]\n[Route("[controller]")]\npublic class WeatherForecastController : ControllerBase\n{\n    [HttpGet]\n    public IActionResult Get()\n    {\n        return Ok(new { message = "Hello from ArchiTech .NET!" });\n    }\n}',
    'ArchiTechDotnetApi/Models/WeatherForecast.cs': 'namespace ArchiTechDotnetApi.Models;\n\npublic class WeatherForecast\n{\n    public DateOnly Date { get; set; }\n    public int TemperatureC { get; set; }\n    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);\n    public string? Summary { get; set; }\n}',
    '.gitignore': '# Dependencies\nobj/\nbin/\n\n# IDE\n.vscode/\n.idea/\n\n# Environment variables\n.env\n.env.local\n\n# Logs\n*.log',
    'Dockerfile': 'FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build\nWORKDIR /src\nCOPY ["ArchiTechDotnetApi/ArchiTechDotnetApi.csproj", "ArchiTechDotnetApi/"]\nRUN dotnet restore "ArchiTechDotnetApi/ArchiTechDotnetApi.csproj"\nCOPY . .\nWORKDIR "/src/ArchiTechDotnetApi"\nRUN dotnet build "ArchiTechDotnetApi.csproj" -c Release -o /app/build\n\nFROM build AS publish\nRUN dotnet publish "ArchiTechDotnetApi.csproj" -c Release -o /app/publish /p:UseAppHost=false\n\nFROM mcr.microsoft.com/dotnet/aspnet:8.0\nWORKDIR /app\nCOPY --from=publish /app/publish .\nEXPOSE 8080\nENTRYPOINT ["dotnet", "ArchiTechDotnetApi.dll"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - "8080:8080"',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.\nPlease replace this content with your own documentation.'
  }
});

// Node.js/Express Schema
const getNodeExpressSchema = () => ({
  language: 'Node.js/Express',
  projectName: 'architech-express-api',
  dependencies: ['express', 'cors', 'helmet', 'compression', 'dotenv', 'winston', 'mongoose'],
  database: 'mongodb',
  directoryTree: {
    paths: [
      'package.json',
      'src/server.js',
      'src/app.js',
      'src/routes/index.js',
      'src/routes/userRoutes.js',
      'src/controllers/userController.js',
      'src/middleware/errorHandler.js',
      'src/utils/logger.js',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md',
      '.env'
    ]
  },
  fileContents: {
    'package.json': JSON.stringify({
      name: "architech-express-api",
      version: "1.0.0",
      description: "Production-grade Express API",
      main: "src/server.js",
      scripts: {
        start: "node src/server.js",
        dev: "nodemon src/server.js"
      },
      dependencies: {
        express: "^4.18.2",
        cors: "^2.8.5",
        helmet: "^7.1.0",
        compression: "^1.7.4",
        dotenv: "^16.4.5",
        winston: "^3.11.0",
        mongoose: "^8.0.0"
      },
      devDependencies: {
        nodemon: "^3.0.1"
      }
    }, null, 2),
    'src/server.js': 'const app = require(\'./app\');\nconst PORT = process.env.PORT || 3000;\n\napp.listen(PORT, () => {\n  console.log(`🚀 Server running on port ${PORT}`);\n});',
    'src/app.js': 'const express = require(\'express\');\nconst cors = require(\'cors\');\nconst helmet = require(\'helmet\');\nconst compression = require(\'compression\');\nconst routes = require(\'./routes\');\n\nconst app = express();\n\napp.use(helmet());\napp.use(cors());\napp.use(compression());\napp.use(express.json());\n\napp.use(\'/api\', routes);\n\nmodule.exports = app;',
    'src/routes/index.js': 'const express = require(\'express\');\nconst router = express.Router();\nconst userRoutes = require(\'./userRoutes\');\n\nrouter.use(\'/users\', userRoutes);\n\nrouter.get(\'/\', (req, res) => {\n  res.json({ message: \'Hello from ArchiTech Express API!\' });\n});\n\nmodule.exports = router;',
    'src/routes/userRoutes.js': 'const express = require(\'express\');\nconst router = express.Router();\nconst userController = require(\'../controllers/userController\');\n\nrouter.get(\'/\', userController.getAllUsers);\n\nmodule.exports = router;',
    'src/controllers/userController.js': 'exports.getAllUsers = async (req, res, next) => {\n  try {\n    res.status(200).json({ success: true, data: [] });\n  } catch (error) {\n    next(error);\n  }\n};',
    'src/middleware/errorHandler.js': 'exports.notFound = (req, res) => {\n  res.status(404).json({ success: false, message: \'Resource not found\' });\n};\n\nexports.globalErrorHandler = (err, req, res, next) => {\n  res.status(err.status || 500).json({ success: false, message: err.message || \'Internal server error\' });\n};',
    'src/utils/logger.js': 'const winston = require(\'winston\');\n\nconst logger = winston.createLogger({\n  level: \'info\',\n  format: winston.format.json(),\n  transports: [new winston.transports.Console()]\n});\n\nmodule.exports = logger;',
    '.gitignore': 'node_modules/\n.env\n*.log',
    'Dockerfile': 'FROM node:20-slim\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.',
    '.env': 'PORT=3000\nNODE_ENV=development'
  }
});

// Python/FastAPI Schema
const getPythonFastAPISchema = () => ({
  language: 'Python/FastAPI',
  projectName: 'architech-fastapi',
  dependencies: ['fastapi', 'uvicorn', 'pydantic-settings', 'sqlalchemy', 'python-jose', 'passlib', 'python-multipart', 'python-dotenv', 'loguru'],
  database: 'sqlite',
  directoryTree: {
    paths: [
      'requirements.txt',
      'main.py',
      'app/__init__.py',
      'app/api/__init__.py',
      'app/api/v1/__init__.py',
      'app/api/v1/users.py',
      'app/core/config.py',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md',
      '.env'
    ]
  },
  fileContents: {
    'requirements.txt': 'fastapi==0.115.0\nuvicorn[standard]==0.32.0\npydantic-settings==2.6.0\nsqlalchemy==2.0.35\npython-jose[cryptography]==3.3.0\npasslib[bcrypt]==1.7.4\npython-multipart==0.0.12\npython-dotenv==1.0.1\nloguru==0.7.2',
    'main.py': 'from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp = FastAPI(title="ArchiTech FastAPI", version="1.0.0")\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],\n    allow_credentials=True,\n    allow_methods=["*"],\n    allow_headers=["*"],\n)\n\n@app.get("/")\nasync def root():\n    return {"message": "Hello from ArchiTech FastAPI!"}',
    'app/__init__.py': '',
    'app/api/__init__.py': '',
    'app/api/v1/__init__.py': '',
    'app/api/v1/users.py': 'from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get("/")\nasync def get_users():\n    return {"message": "Users endpoint"}\n',
    'app/core/config.py': 'from pydantic_settings import BaseSettings\n\nclass Settings(BaseSettings):\n    app_name: str = "ArchiTech App"\n\nsettings = Settings()',
    '.gitignore': '__pycache__/\nvenv/\n.env\n*.log',
    'Dockerfile': 'FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - "8000:8000"',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.',
    '.env': 'APP_NAME=ArchiTech App'
  }
});

// C++/CMake Schema
const getCppCMakeSchema = () => ({
  language: 'C++/CMake',
  projectName: 'architech-cpp-app',
  dependencies: [],
  database: 'sqlite',
  directoryTree: {
    paths: [
      'CMakeLists.txt',
      'src/main.cpp',
      'include/App.h',
      'src/App.cpp',
      '.gitignore',
      'Dockerfile',
      'docker-compose.yml',
      'README.md'
    ]
  },
  fileContents: {
    'CMakeLists.txt': 'cmake_minimum_required(VERSION 3.10)\nproject(ArchiTechCppApp)\nset(CMAKE_CXX_STANDARD 17)\n\nadd_executable(ArchiTechCppApp src/main.cpp src/App.cpp)\ntarget_include_directories(ArchiTechCppApp PRIVATE include)',
    'src/main.cpp': '#include <iostream>\n#include "App.h"\n\nint main() {\n    std::cout << "Hello from ArchiTech C++!" << std::endl;\n    App app;\n    app.run();\n    return 0;\n}',
    'include/App.h': '#ifndef APP_H\n#define APP_H\n\nclass App {\npublic:\n    void run();\n};\n\n#endif',
    'src/App.cpp': '#include "App.h"\n#include <iostream>\n\nvoid App::run() {\n    std::cout << "ArchiTech C++ Application is running!" << std::endl;\n}',
    '.gitignore': 'build/\n*.o\nArchiTechCppApp',
    'Dockerfile': 'FROM gcc:latest\nWORKDIR /usr/src/myapp\nCOPY . .\nRUN apt-get update && apt-get install -y cmake\nRUN cmake . && make\nCMD ["./ArchiTechCppApp"]',
    'docker-compose.yml': 'version: \'3.8\'\nservices:\n  app:\n    build: .',
    'README.md': '# ArchiTech Generated Project\nThis file was generated by ArchiTech scaffolder.'
  }
});

module.exports = { analyzePrompt };
