const fs = require('fs');
const path = require('path');

const generateCode = (schema, outputDir, projectType) => {
  const logs = [];
  let previewFileContent = '';

  try {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
      logs.push(`Created directory: ${outputDir}`);
    }

    schema.folders.forEach((folder) => {
      const folderPath = path.join(outputDir, folder);
      if (!fs.existsSync(folderPath)) {
        fs.mkdirSync(folderPath, { recursive: true });
        logs.push(`Created folder: ${folder}`);
      }
    });

    Object.keys(schema.files).forEach((file) => {
      const filePath = path.join(outputDir, file);
      let content = '';

      if (file.endsWith('main.py')) {
        content = `from fastapi import FastAPI
from app.api import router
from app.core.config import settings

app = FastAPI(title="ArchiTech Generated App")

app.include_router(router)

@app.get("/")
async def root():
    return {"message": "Hello from ArchiTech!"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`;
        previewFileContent = content;
      } else if (file.endsWith('config.py')) {
        content = `from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    app_name: str = "ArchiTech App"
    redis_url: str = "redis://localhost:6379"
    
    class Config:
        env_file = ".env"

settings = Settings()`;
      } else if (file.endsWith('api/__init__.py')) {
        content = `from fastapi import APIRouter

router = APIRouter()

@app.get("/health")
async def health_check():
    return {"status": "healthy"}`;
      } else if (file.endsWith('requirements.txt')) {
        content = `fastapi==0.109.0
uvicorn==0.27.0
pydantic-settings==2.1.0
redis==5.0.1`;
      } else if (file.endsWith('.env')) {
        content = `APP_NAME=ArchiTech App
REDIS_URL=redis://redis:6379`;
      } else if (file.endsWith('server.js')) {
        content = `const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.json({ message: "Hello from ArchiTech!" });
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});`;
        previewFileContent = content;
      } else if (file.endsWith('routes/index.js')) {
        content = `const express = require('express');
const router = express.Router();

router.get("/health", (req, res) => {
  res.json({ status: "healthy" });
});

module.exports = router;`;
      } else if (file.endsWith('App.jsx')) {
        content = `function App() {
  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold">Hello from ArchiTech!</h1>
    </div>
  );
}

export default App;`;
        previewFileContent = content;
      } else if (file.endsWith('main.jsx')) {
        content = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;
      } else if (file.endsWith('index.html')) {
        content = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ArchiTech App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
      } else if (file.endsWith('package.json') && file.includes('src') === false) {
        content = JSON.stringify({
          name: "architech-generated-app",
          version: "1.0.0",
          scripts: {
            dev: "vite",
            build: "vite build",
            preview: "vite preview",
            start: "node src/server.js"
          },
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            express: "^4.18.2",
            cors: "^2.8.5"
          },
          devDependencies: {
            "@types/react": "^18.2.43",
            "@types/react-dom": "^18.2.17",
            "@vitejs/plugin-react": "^4.2.1",
            vite: "^5.0.8"
          }
        }, null, 2);
      } else if (file.endsWith('main.cpp')) {
        content = `#include <iostream>

int main() {
  std::cout << "Hello from ArchiTech C++!" << std::endl;
  return 0;
}`;
        previewFileContent = content;
      } else if (file.endsWith('Makefile')) {
        content = `CC=g++
CFLAGS=-Wall -Wextra -std=c++17

all: ArchiTechCppApp

ArchiTechCppApp: src/main.cpp
\t$(CC) $(CFLAGS) -o ArchiTechCppApp src/main.cpp

clean:
\trm -f ArchiTechCppApp`;
      } else if (file.endsWith('README.md')) {
        content = `# ArchiTech Generated Project

This project was generated by ArchiTech.

## Getting Started

Follow the instructions below to run this project.`;
      }

      fs.writeFileSync(filePath, content);
      logs.push(`Created file: ${file}`);
    });

    // Add CMakeLists.txt for C++ projects
    if (projectType === 'cpp') {
      const cmakePath = path.join(outputDir, 'CMakeLists.txt');
      const cmakeContent = `cmake_minimum_required(VERSION 3.10)
project(ArchiTechCppApp)

set(CMAKE_CXX_STANDARD 17)

add_executable(ArchiTechCppApp src/main.cpp)
`;
      fs.writeFileSync(cmakePath, cmakeContent);
      logs.push('Created file: CMakeLists.txt');
    }

    return {
      success: true,
      logs,
      previewFileContent,
      message: 'Code Writer generated all files successfully'
    };
  } catch (error) {
    return {
      success: false,
      logs,
      error: error.message,
      message: 'Code Writer encountered an error'
    };
  }
};

module.exports = { generateCode };
